name: AIronman
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2
  - numpy
  - pandas
  - pip:
      - garminconnect
      - crewai
      - fitdecode
      - fitparse
